name: check
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: action/checkout@v4
      - name: run setup
        run: make setup
      - name: run test
        run: make test
      - name: run lint
        run: make lint
